### ISSUE TITLE
Make github action template

### ISSUE THREAD

**Issue by joemarshall** [pyodide/pytest-pyodide#38]
It would be great to have a github action template for this - 

So in other projects to have a complete build and test one could just do something like:

```
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.10.2
    - uses: mymindstorm/setup-emsdk@v11
      with:
        version: 3.1.14
    - run: pip install pyodide-build==0.21.0
    - run: pyodide build    
    - uses: pyodide/pytest-pyodide@v1
       with:
         pyodide-versions: [0.21.0]
         browsers: [chrome,firefox]
         os: [linux,macos]
         test-folder: tests
```

It would save duplicated complexity in other projects (check out the CI actions in this repo, and the similar stuff in micropip for example)

**Comment by joemarshall** [comment]
Even crazier would be to make a further action in pyodide-build, so you could just do a pyodide build of a package and test it in CI automatically. So adding a pyodide build and test to CI for a package would in theory be as simple as this:
```
- uses:  pyodide/pyodide-build@v1
  with:
    pyodide-versions:[0.21.0]
    test-browsers: []
    test-os: []
    test-folder:tests
    artifact-name: my lovely pyodide wheel
```
